# This is the list of command-to-keystroke mappings that are configurable in Preferences>Keys.
# The list does not necessarily contain all commands and all keystrokes in RIDE, only those in Preferences>Keys.

@cmds = [
#  code   description                 defaults                  important? (shown in lbar's kbd btn tooltip)
  ['QT',  'Quit (and lose changes)',  ['Shift-Esc'],            1]
  ['TB',  'Tab between windows',      ['Ctrl-Tab'],             1]
  ['BT',  'Back Tab between windows', ['Shift-Ctrl-Tab'],       1]
  ['EP',  'Exit (and save changes)',  ['Esc'],                  1]
  ['FD',  'Forward or Redo',          ['Shift-Ctrl-Enter'],     1]
  ['BK',  'Backward or Undo',         ['Shift-Ctrl-Backspace'], 1]
  ['SC',  'Search (in editors)',      [],                       1]
  ['RP',  'Replace (in editors)',     [],                       1]
  ['ED',  'Edit',                     ['Shift-Enter'],          1]
  ['TC',  'Trace',                    ['Ctrl-Enter'],           1]
  ['TL',  'Toggle localisation',      ['Ctrl-Up'],              1]
  ['ER',  'Execute line',             ['Enter']]
  ['WI',  'Weak interrupt',           ['Ctrl-Pause']]
  ['SI',  'Strong interrupt',         []]
  ['PRF', 'Show preferences',         []]
  ['NEW', 'New session',              ['Ctrl-N']]
  ['CNC', 'Connect',                  []]
  ['QIT', 'Quit',                     ['Ctrl-Q']]
  ['HLP', 'Help',                     ['F1']]
  ['ABT', 'About',                    ['Shift-F1']]
  ['BP',  'Toggle breakpoint',        []]
  ['TO',  'Toggle fold',              []]
  ['AO',  'Add comments',             []]
  ['DO',  'Delete comments',          []]
  ['AC',  'Align comments',           []]
  ['LN',  'Toggle line numbers',      []]
  ['LBR', 'Toggle language bar',      []]
  ['ZMI', 'Increase font size',       ['Ctrl-=', 'Shift-Ctrl-=']]
  ['ZMO', 'Decrease font size',       ['Ctrl--']]
  ['ZMR', 'Reset font size',          ['Ctrl-0']]
  ['DMR', 'Load demo file',           []]
  ['DMN', 'Next line in demo',        []]
  ['DMP', 'Previous line in demo',    []]
  ['DMK', 'Toggle key display mode',  []]
]
