#!/bin/sh
# if ! grep -qw vfpv3 /proc/cpuinfo ; then
# 	MSG="Ride is not supported on this hardware."
# 	zenity --warning --text="$MSG" 2> /dev/null || echo "$MSG" >&2
# 	exit 1
# fi
D="$(dirname "$(readlink -e "$0")")"
exec "$D/EXECUTABLE" "$@"
