D.sqglDesc={
  '←':'Left Arrow',
  '+':'Plus',
  '-':'Minus',
  '×':'Times',
  '÷':'Divide',
  '*':'Star',
  '⍟':'Log',
  '⌹':'Domino',
  '○':'Circle',
  '!':'Exclamation Mark',
  '?':'Question Mark',
  '|':'Stile',
  '⌈':'Upstile',
  '⌊':'Downstile',
  '⊥':'Up Tack',
  '⊤':'Down Tack',
  '⊣':'Left Tack',
  '⊢':'Right Tack',
  '=':'Equal',
  '≠':'Not Equal',
  '≤':'Less Than Or Equal To',
  '<':'Less Than',
  '>':'Greater Than',
  '≥':'Greater Than Or Equal To',
  '≡':'Equal Underbar',
  '≢':'Equal Underbar Slash',
  '∧':'Logical AND',
  '∨':'Logical OR',
  '⍲':'Logical NAND',
  '⍱':'Logical NOR',
  '↑':'Up Arrow',
  '↓':'Down Arrow',
  '⊂':'Left Shoe',
  '⊃':'Right Shoe',
  '⌷':'Squad',
  '⍋':'Grade Up',
  '⍒':'Grade Down',
  '⍳':'Iota',
  '⍷':'Epsilon Underbar',
  '∪':'Down Shoe',
  '∩':'Up Shoe',
  '∊':'Epsilon',
  '~':'Tilde',
  '/':'Slash',
  '\\':'',
  '⌿':'Slash Bar',
  '⍀':'Backslash Bar',
  ',':'Comma',
  '⍪':'Comma Bar',
  '⍴':'Rho',
  '⌽':'Circle Stile',
  '⊖':'Circle Bar',
  '⍉':'Transpose',
  '¨':'Diaeresis',
  '⍨':'Tilde Diaeresis',
  '⍣':'Star Diaeresis',
  '.':'Dot',
  '∘':'Jot',
  '⍤':'Jot Diaeresis',
  '⍞':'Quote Quad',
  '⎕':'Quad',
  '⍠':'Quad Colon',
  '⌸':'Quad Equal',
  '⍎':'Hydrant',
  '⍕':'Thorn',
  '⋄':'Diamond',
  '⍝':'Lamp',
  '→':'Right Arrow',
  '⍵':'Omega',
  '⍺':'Alpha',
  '∇':'Del',
  '&':'Ampersand',
  '¯':'High Minus',
  '⍬':'Zilde',
  '⌶':'I-Beam',
  '¤':'',
  '∥':'',
  '∆':'',
  '⍙':'',
  '⍥':'',
  '⍫':'',
  'Á':'',
  '⍸':'Iota Underbar',
  '⊆':'Left Shoe Underbar',
  '@':'At',
  '⌺':'Quad Diamond',
}

//backquote-backquote name completions
//mentioned in http://wiki.dyalog.bramley/index.php/New_Glyphs
D.informal=[
  //'squiggle alias0 alias1 ...'
  '← leftarrow assign gets is copula',
  '+ plus add conjugate mate',
  '- minus hyphen subtract negate',
  '× cross times multiply sgn signum direction',
  '÷ divide reciprocal obelus',
  '* star asterisk power exponential',
  '⍟ logarithm naturallogarithm circlestar starcircle splat',
  '⌹ domino matrixdivide matrixinverse quaddivide leastsquares',
  '○ pi circular trigonometric hyperbolic complex imaginary',
  '! exclamation bang shriek factorial binomial combinations',
  '? question roll deal random',
  '| stile stroke verticalline modulo abs magnitude residue remainder',
  '⌈ upstile maximum ceiling',
  '⌊ downstile minimum floor',
  '⊥ base decode uptack',
  '⊤ antibase encode downtack representation',
  '⊣ left lev lefttack sameleft',
  '⊢ right dex righttack sameright',
  '= equal xnor logicalxnor',
  '≠ ne notequal xor logicalxor',
  '≤ le lessorequal fore logicalimplication',
  '< lessthan before',
  '> greaterthan after',
  '≥ ge greaterorequal aft',
  '≡ match equalunderbar identical depth',
  '≢ notmatch natch equalunderbarslash notidentical tally',
  '∧ and conjunction lcm logicaland lowestcommonmultiple caret',
  '∨ or disjunction gcd vel logicalor greatestcommondivisor hcf highestcommonfactor',
  '⍲ nand notand andtilde logicalnand carettilde',
  '⍱ nor notor ortilde logicalnor',
  '↑ uparrow mix take',
  '↓ downarrow split drop',
  '⊂ enclose leftshoe partitionedenclose',
  '⊃ disclose rightshoe pick first',
  '⌷ squishquad squad index default materialise',
  '⍋ gradeup deltastile upgrade pine',
  '⍒ gradedown delstile downgrade spine',
  '⍳ iota indices indexof',
  '⍷ find epsilonunderbar',
  '∪ cup union unique downshoe distinct',
  '∩ cap intersection upshoe',
  '∊ epsilon in membership enlist flatten type',
  '~ tilde not logicalnot without except',
  '/ slash reduce fold insert select compress replicate solidus',
  '\\ backslash slope scan expand cumulativereduce',
  '⌿ slashbar reducefirst foldfirst insertfirst',
  '⍀ slopebar backslashbar scanfirst expandfirst',
  ', comma catenate laminate ravel concatenate',
  '⍪ commabar table catenatefirst concatenatefirst',
  '⍴ rho shape reshape',
  '⌽ reverse rotate circlestile',
  '⊖ reversefirst rotatefirst circlebar rowel upset',
  '⍉ transpose circlebackslash cant diagonal',
  '¨ each diaeresis',
  '⍨ commute switch selfie tildediaeresis swap',
  '⍣ poweroperator stardiaeresis powerlimit fixedpoint fixpoint converge while',
  '. dotproduct innerproduct namespaceseparator',
  '∘ jot compose bind curry ring outerproduct',
  '⍤ jotdiaeresis rank paw',
  '⍞ quotequad input output characterinput rawinput',
  '⎕ quad evaluatedinput',
  '⍠ colonquad quadcolon variant option',
  '⌸ equalquad quadequal key group',
  '⍎ execute eval uptackjot hydrant',
  '⍕ format downtackjot thorn',
  '⋄ diamond statementseparator',
  '⍝ comment lamp',
  '→ rightarrow branch abort goto',
  '⍵ omega rightarg',
  '⍺ alpha leftarg',
  '∇ del recurse triangledown downtriangle carrot',
  '& ampersand spawn et',
  '¯ macron negative highminus',
  '⍬ zilde empty',
  '⌶ ibeam',
  '¤ currency isolate',
  '∥ parallel',
  '∆ delta triangleup uptriangle',
  '⍙ deltaunderbar',
  '⍥ circlediaeresis hoof holler',
  '⍫ deltilde',
  'Á aacute underscoredalphabet',
  '⍸ where intervalindex iotaunderbar',
  '⊆ leftshoeunderbar encloseifsimple conditionalenclose partition nest',
  '@ at substitute merge amend',
  '⌺ diamondquad quaddiamond stencil tessellate tile',
]
for(var i=0;i<26;i++)D.informal.push(String.fromCharCode(i+0x24b6)+' _'+String.fromCharCode(i+0x61/*a*/)) //Ⓐ _a
