// This is the list of command-to-keystroke mappings that are configurable in Preferences>Keys.
// The list does not necessarily contain all commands and all keystrokes in RIDE,
// only those in Preferences>Keys.
// Some of the codes are inherited from Dyalog's old IDE
// (see ../docs/cmd-codes.txt and near the end of km.js)
// Others were made up for RIDE's purposes - those use no fewer than three letters.
D.cmds = [
  /* eslint-disable */
  //code description                default keys
  ['ABT','About',                   ['Shift-F1']],
  ['AC', 'Align comments',          []],
  ['AO', 'Comment out lines',       []],
  ['BK', 'Backward or Undo',        ['Shift-Ctrl-Backspace']],
  ['BP', 'Toggle breakpoint',       []],
  ['BT', 'Back Tab between windows',['Shift-Ctrl-Tab']],
  ['CNC','Connect',                 []],
  ['DMK','Toggle key display mode', []],
  ['DMN','Next line in demo',       []],
  ['DMP','Previous line in demo',   []],
  ['DMR','Load demo file',          []],
  ['DO', 'Uncomment lines',         []],
  ['ED', 'Edit',                    ['Shift-Enter']],
  ['EMD','Edit Mode',               ['Shift-F3']],
  ['EP', 'Exit (and save changes)', ['Esc']],
  ['ER', 'Execute line',            ['Enter']],
  ['EXP','Expand selection',        ['Shift-Alt-Up']],
  ['FD', 'Forward or Redo',         ['Shift-Ctrl-Enter']],
  ['FX', 'Fix the current function',[]],
  ['HLP','Help',                    ['F1']],
  ['JBK','Jump back',               ['Shift-Ctrl-J']],
  ['JSC','Show JavaScript console', ['F12']],
  ['LBR','Toggle language bar',     []],
  ['LN', 'Toggle line numbers',     []],
  ['LOG','Show RIDE protocol log',  ['Ctrl-F12']],
  ['MA', 'Continue execution of all threads',[]],
  ['NEW','New session',             ['Ctrl-N']],
  ['NX' ,'Next match',              []],
  ['PF1' ,'',                       []],
  ['PF2' ,'',                       ['F2']],
  ['PF3' ,'',                       ['F3']],
  ['PF4' ,'',                       ['F4']],
  ['PF5' ,'',                       ['F5']],
  ['PF6' ,'',                       ['F6']],
  ['PF7' ,'',                       ['F7']],
  ['PF8' ,'',                       ['F8']],
  ['PF9' ,'',                       ['F9']],
  ['PF10','',                       ['F10']],
  ['PF11','',                       []],
  ['PF12','',                       []],
  ['PRF','Show preferences',        []],
  ['PV' ,'Previous match',          []],
  ['QIT','Quit',                    (D.mac?['Cmd-Q']:[]).concat('Ctrl-Q')],
  ['QT', 'Quit (and lose changes)', ['Shift-Esc']],
  ['RD', 'Reformat',                ['NumpadDivide']],
  ['RP', 'Replace',                 []],
  ['SC', 'Search',                  ['Ctrl-F']],
  ['SI', 'Strong interrupt',        []],
  ['STL','Skip to line',            []],
  ['TB', 'Tab between windows',     ['Ctrl-Tab']],
  ['TC', 'Trace',                   ['Ctrl-Enter']],
  ['TGC','Toggle comment',          []],
  ['TIP','Show value tip',          []],
  ['TL', 'Toggle localisation',     ['Ctrl-Up']],
  ['TO', 'Toggle fold',             []],
  ['TVB','Toggle view stops',       []],
  ['TVO','Toggle view outline',     []],
  ['TR', 'Refresh threads',         []],
  ['VAL','Evaluate selection or name under cursor',[]],
  ['WI', 'Weak interrupt',          ['Ctrl-Pause']],
  ['WSE','Toggle workspace explorer',[]],
  ['ZM', 'Toggle maximise editor',  []],
  ['ZMI','Increase font size',      (D.mac?['Cmd-=','Shift-Cmd-=']:[]).concat(['Ctrl-=','Shift-Ctrl-='])],
  ['ZMO','Decrease font size',      (D.mac?['Cmd--']:[]).concat('Ctrl--')],
  ['ZMR','Reset font size',         (D.mac?['Cmd-0']:[]).concat('Ctrl-0')],
  /* eslint-enable */
];
