//generated by tools/kbds-gen.js
D.kbds={
  geom:{"_":"iso","en_US":"ansi","en_US_Mac":"ansi"},
  layouts:{
    da_DK:[
      " ½1234567890+´   qwertyuiopå¨  asdfghjklæø'  <zxcvbnm,.-  ",
      " §!\"#¤%&/()=?`   QWERTYUIOPÅ^  ASDFGHJKLÆØ*  >ZXCVBNM;:_  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕   ⊢⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬     ⍛  ⍤⌸⌷≡≢   ⊣⊆      ⍪⍙⍠  "
    ],
    da_DK_Mac:[
      " $1234567890+´   qwertyuiopå¨  asdfghjklæø'  <zxcvbnm,.-  ",
      " §!\"#€%&/()=?`   QWERTYUIOPÅ^  ASDFGHJKLÆØ*  >ZXCVBNM;:_  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕   ⊢⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬     ⍛  ⍤⌸⌷≡≢   ⊣⊆      ⍪⍙⍠  "
    ],
    de_DE:[
      " ^1234567890ß´   qwertzuiopü+  asdfghjklöä#  <yxcvbnm,.-  ",
      " °!\"§$%&/()=?`   QWERTZUIOPÜ*  ASDFGHJKLÖÄ'  >YXCVBNM;:_  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕#  ⊢⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬     ⍛  ⍤⌸⌷≡≢   ⊣⊆      ⍪⍙⍠  "
    ],
    en_GB:[
      " `1234567890-=   qwertyuiop[]  asdfghjkl;'#  \\zxcvbnm,./  ",
      " ¬!\"£$%^&*()_+   QWERTYUIOP{}  ASDFGHJKL:@~  |ZXCVBNM<>?  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕   ⊢⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬     ⍛  ⍤⌸⌷≡≢   ⊣⊆      ⍪⍙⍠  "
    ],
    en_GB_Mac:[
      " §1234567890-=   qwertyuiop[]  asdfghjkl;'\\  `zxcvbnm,./  ",
      " ±!@£$%^&*()_+   QWERTYUIOP{}  ASDFGHJKL:\"|  ~ZXCVBNM<>?  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕#  ⊢⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬     ⍛  ⍤⌸⌷≡≢   ⊣⊆      ⍪⍙⍠  "
    ],
    en_US:[
      " `1234567890-=   qwertyuiop[]\\ asdfghjkl;'    zxcvbnm,./  ",
      " ~!@#$%^&*()_+   QWERTYUIOP{}| ASDFGHJKL:\"    ZXCVBNM<>?  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→⊢ ⍺⌈⌊_∇∆∘'⎕⍎⍕    ⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬⊣    ⍛  ⍤⌸⌷≡≢    ⊆      ⍪⍙⍠  "
    ],
    en_US_Mac:[
      " `1234567890-=   qwertyuiop[]\\ asdfghjkl;'    zxcvbnm,./  ",
      " ~!@#$%^&*()_+   QWERTYUIOP{}| ASDFGHJKL:\"    ZXCVBNM<>?  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→⊢ ⍺⌈⌊_∇∆∘'⎕⍎⍕    ⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬⊣    ⍛  ⍤⌸⌷≡≢    ⊆      ⍪⍙⍠  "
    ],
    es_ES:[
      " º1234567890'¡   qwertyuiop`+  asdfghjklñ´ç  <zxcvbnm,.-  ",
      " ª!\"·$%&/()=?¿   QWERTYUIOP^*  ASDFGHJKLÑ¨Ç  >ZXCVBNM;:_  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕#  ⊢⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬     ⍛  ⍤⌸⌷≡≢   ⊣⊆      ⍪⍙⍠  "
    ],
    fi_FI:[
      " §1234567890+'   qwertyuiopå¨  asdfghjklöä'  <zxcvbnm,.-  ",
      " ⍬!\"#⊢%&/()=?`   QWERTYUIOPÅ^  ASDFGHJKLÖÄ*  >ZXCVBNM;:_  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕≡  ⍙⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺≡⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸ ⍣⍞⍬     ⍛   ⌸⌷[]⍷  ⌷⊆      ⍪ ⍨  "
    ],
    fi_FI_Mac:[
      " §1234567890+´   qwertyuiopå¨  asdfghjklöä'  <zxcvbnm,.-  ",
      " °!\"#€%&/()=?`   QWERTYUIOPÅ^  ASDFGHJKLÖÄ*  >ZXCVBNM;:_  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕   ⊢⊂⊃∩∪⊥⊤|⍝⍀⌿  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷ ⍨  ⍸⍥⍣⍞⍬     ⍛  ⍤⌸⌷≡≢   ⊣⊆      ⍪⍙⍠  "
    ],
    fr_BE:[
      " ²&é\"'(§è!çà)-   azertyuiop^$  qsdfghjklmùμ  <wxcvbn,;:=  ",
      " ³1234567890°_   AZERTYUIOP¨*  QSDFGHJKLM%£  >WXCVBN?./+  ",
      " ⋄¨¯<≤=≥>≠∨^÷×   ⍺⍵∊⍴~↑↓⍳○*←→  ?⌈⌊_∇∆∘'⎕|[]  ⊢⊂⊃∩∪⊥⊤≡≢ ⍀  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲⍬⌹     ⍷ ⍨  ⍸⍥⍣⍞⍙     ⍛  ⍤⌸⌷ ⍎⍕  ⊣⊆     ⍪⍝⌿⍠  "
    ],
    fr_FR:[
      " ²&é\"'(-è_çà)=   azertyuiop^$  qsdfghjklmù*  <wxcvbn,;:!  ",
      "  1234567890°+   AZERTYUIOP¨£  QSDFGHJKLM%μ  >WXCVBN?./§  ",
      " ⋄¨¯<≤=≥>≠∨∧÷×   ⍺⍵∊⍴~↑↓⍳○*←→  ?⌈⌊_∇∆∘'⎕|[]  ⊢⊂⊃∩∪⊥⊤≡≢ ⍀  ",
      " ⌺⌶⍫⍒⍋⌽⍉⊖⍟⍱⍲⍬⌹     ⍷ ⍨  ⍸⍥⍣⍞⍙     ⍛  ⍤⌸⌷ ⍎⍕  ⊣⊆     ⍪⍝⌿⍠  "
    ],
    it_IT:[
      " \\1234567890'ì   qwertyuiopè+  asdfghjklòàù  <zxcvbnm,.-  ",
      " |!\"£$%&/()=?^   QWERTYUIOPé*  ASDFGHJKLç°§  >ZXCVBNM;:_  ",
      " ⋄¨¯<≤=≥>≠∨∧×÷   ?⍵∊⍴~↑↓⍳○*←→  ⍺⌈⌊_∇∆∘'⎕⍎⍕⊢  ≡    ⊥⊤∣⍝⍀/  ",
      " ⌺⍨⍫⍒⍋⌽⍉⊖⍟⍱⍲!⌹     ⍷  ⍸ ⌶⍥⍣⍞⍬     ⍛ ⍙⍤⌸⌷()⊣  ≢⊂⊃∩∪   ⍪⍠\\  "
    ]
  }
}
